version: '3'

services:

  portfolio:
    build: ./portfolio-app
    container_name: portfolio-container
    ports:
      - "5000:5000"

  javaapp:
    build: ./java-app
    container_name: java-container
    ports:
      - "8080:8080"
